<a href="https://colab.research.google.com/github/olyadiya/Intro_to_ML/blob/main/trees_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание: cравнение древовидных алгоритмов на NLP-данных

**Задача:** oбучить разные древовидные модели на текстах новостей, замерить test accuracy и время обучения, заполнить таблицы.

## 1. Загрузка и подготовка данных (код дан)

In [1]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import time
import pandas as pd

# Загружаем 3 категории
categories = ['rec.sport.baseball', 'sci.space', 'comp.graphics']
newsgroups = fetch_20newsgroups(subset='all', categories=categories, shuffle=True, random_state=42)

# TF-IDF векторизация
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2), stop_words='english')
X = vectorizer.fit_transform(newsgroups.data)
y = newsgroups.target

# Разделение на train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Размер обучающей выборки: {X_train.shape}")
print(f"Размер тестовой выборки: {X_test.shape}")

Размер обучающей выборки: (2363, 5000)
Размер тестовой выборки: (591, 5000)


## 2. Образец: Дерево решений (Decision Tree)

**Гиперпараметр:** `max_depth`

In [2]:
from sklearn.tree import DecisionTreeClassifier

results_tree = []

# Образец: мы делаем перебор значений max_depth = [3, 5, 10, 20, None])
# Для каждого: замер времени, обучение, accuracy на тесте, сохранение в results_tree

for depth in [3, 5, 10, 20, None]:
    start = time.time()
    clf = DecisionTreeClassifier(max_depth=depth, random_state=42)
    clf.fit(X_train, y_train)
    fit_time = time.time() - start
    acc = accuracy_score(y_test, clf.predict(X_test))
    results_tree.append({'max_depth': depth, 'test_accuracy': round(acc, 4), 'time_sec': round(fit_time, 2)})
    print(f"depth={depth}: acc={acc:.4f}, time={fit_time:.2f}s")

df_tree = pd.DataFrame(results_tree)
print("\nТаблица 1. Дерево решений")
print(df_tree.to_markdown(index=False))

depth=3: acc=0.6244, time=0.17s
depth=5: acc=0.6971, time=0.28s
depth=10: acc=0.7716, time=0.51s
depth=20: acc=0.8409, time=0.70s
depth=None: acc=0.8697, time=0.67s

Таблица 1. Дерево решений
|   max_depth |   test_accuracy |   time_sec |
|------------:|----------------:|-----------:|
|           3 |          0.6244 |       0.17 |
|           5 |          0.6971 |       0.28 |
|          10 |          0.7716 |       0.51 |
|          20 |          0.8409 |       0.7  |
|         nan |          0.8697 |       0.67 |


## 3. Заполните таблицы для остальных алгоритмов

По аналогии с образцом обучите следующие модели и запишите результаты.

### 3.1. Случайный лес (Random Forest)

**Гиперпараметр:** `max_depth` (фиксируем `n_estimators=100`)

| max_depth | test_accuracy | time_sec |
|-----------|---------------|----------|
| 5         |               |          |
| 10        |               |          |
| 20        |               |          |
| None      |               |          |

In [14]:
from sklearn.ensemble import RandomForestClassifier

results_rf = []

for depth in [5, 10, 20, None]:
    start = time.time()
    clf = RandomForestClassifier(max_depth=depth, n_estimators=100, random_state=42)
    clf.fit(X_train, y_train)
    fit_time = time.time() - start
    acc = accuracy_score(y_test, clf.predict(X_test))
    results_rf.append({'max_depth': depth, 'test_accuracy': round(acc, 4), 'time_sec': round(fit_time, 2)})
    print(f"max_depth={depth}: acc={acc:.4f}, time={fit_time:.2f}s")

df_rf = pd.DataFrame(results_rf)
print("\nТаблица 2. Случайный лес")
print(df_rf.to_markdown(index=False))

max_depth=5: acc=0.9002, time=0.64s
max_depth=10: acc=0.9154, time=1.04s
max_depth=20: acc=0.9357, time=1.93s
max_depth=None: acc=0.9526, time=4.65s

Таблица 2. Случайный лес
|   max_depth |   test_accuracy |   time_sec |
|------------:|----------------:|-----------:|
|           5 |          0.9002 |       0.64 |
|          10 |          0.9154 |       1.04 |
|          20 |          0.9357 |       1.93 |
|         nan |          0.9526 |       4.65 |


### 3.2. Градиентный бустинг (Gradient Boosting)

**Гиперпараметр:** `learning_rate` (фиксируем `n_estimators=100, max_depth=3`)

| learning_rate | test_accuracy | time_sec |
|---------------|---------------|----------|
| 0.01          |               |          |
| 0.05          |               |          |
| 0.1           |               |          |
| 0.5           |               |          |

In [12]:
from sklearn.ensemble import GradientBoostingClassifier

results_gb = []

for lr in [0.01, 0.05, 0.1, 0.5]:
    start = time.time()
    clf = GradientBoostingClassifier(learning_rate=lr, n_estimators=100, max_depth=3, random_state=42)
    clf.fit(X_train, y_train)
    fit_time = time.time() - start
    acc = accuracy_score(y_test, clf.predict(X_test))
    results_gb.append({'learning_rate': lr, 'test_accuracy': round(acc, 4), 'time_sec': round(fit_time, 2)})
    print(f"learning_rate={lr}: acc={acc:.4f}, time={fit_time:.2f}s")

df_gb = pd.DataFrame(results_gb)
print("\nТаблица 3. Градиентный бустинг")
print(df_gb.to_markdown(index=False))

learning_rate=0.01: acc=0.8782, time=40.97s
learning_rate=0.05: acc=0.9475, time=37.35s
learning_rate=0.1: acc=0.9577, time=38.01s
learning_rate=0.5: acc=0.9662, time=36.39s

Таблица 3. Градиентный бустинг
|   learning_rate |   test_accuracy |   time_sec |
|----------------:|----------------:|-----------:|
|            0.01 |          0.8782 |      40.97 |
|            0.05 |          0.9475 |      37.35 |
|            0.1  |          0.9577 |      38.01 |
|            0.5  |          0.9662 |      36.39 |


### 3.3. XGBoost

**Гиперпараметр:** `gamma` (фиксируем `n_estimators=100, learning_rate=0.1`)

| gamma | test_accuracy | time_sec |
|-------|---------------|----------|
| 0     |               |          |
| 0.1   |               |          |
| 0.5   |               |          |
| 1.0   |               |          |

In [25]:
from xgboost import XGBClassifier

results_xgb = []

for gamma_val in [0, 0.1, 0.5, 1.0]:
    start = time.time()
    clf = XGBClassifier(n_estimators=100, learning_rate=0.1, gamma=gamma_val, random_state=42, eval_metric='logloss')
    clf.fit(X_train, y_train)
    fit_time = time.time() - start
    acc = accuracy_score(y_test, clf.predict(X_test))
    results_xgb.append({'gamma': gamma_val,'test_accuracy': round(acc, 4),'time_sec': round(fit_time, 2)})
    print(f"gamma={gamma_val}: acc={acc:.4f}, time={fit_time:.2f} sec")

df_xgb = pd.DataFrame(results_xgb)
print("\nТаблица 4. XGBoost")
print(df_xgb.to_markdown(index=False))

gamma=0: acc=0.9459, time=35.93 sec
gamma=0.1: acc=0.9442, time=34.77 sec
gamma=0.5: acc=0.9492, time=31.58 sec
gamma=1.0: acc=0.9492, time=31.14 sec

Таблица 4. XGBoost
|   gamma |   test_accuracy |   time_sec |
|--------:|----------------:|-----------:|
|     0   |          0.9459 |      35.93 |
|     0.1 |          0.9442 |      34.77 |
|     0.5 |          0.9492 |      31.58 |
|     1   |          0.9492 |      31.14 |


### 3.4. AdaBoost

**Гиперпараметр:** `learning_rate` (фиксируем `n_estimators=100`)

| learning_rate | test_accuracy | time_sec |
|---------------|---------------|----------|
| 0.5           |               |          |
| 1.0           |               |          |
| 1.5           |               |          |
| 2.0           |               |          |

In [17]:
from sklearn.ensemble import AdaBoostClassifier

results_ada = []

for ada in [0.5, 1.0, 1.5, 2.0]:
    start = time.time()
    clf = AdaBoostClassifier(n_estimators=100, learning_rate=lr, random_state=42)
    clf.fit(X_train, y_train)
    fit_time = time.time() - start
    acc = accuracy_score(y_test, clf.predict(X_test))
    results_ada.append({'learning_rate': lr, 'test_accuracy': round(acc, 4), 'time_sec': round(fit_time, 2)})
    print(f"learning_rate={lr}: acc={acc:.4f}, time={fit_time:.2f}s")

df_ada = pd.DataFrame(results_ada)
print("\nТаблица 5. AdaBoost")
print(df_ada.to_markdown(index=False))

learning_rate=0.5: acc=0.8629, time=6.98s
learning_rate=0.5: acc=0.8629, time=5.37s
learning_rate=0.5: acc=0.8629, time=6.13s
learning_rate=0.5: acc=0.8629, time=5.29s

Таблица 5. AdaBoost
|   learning_rate |   test_accuracy |   time_sec |
|----------------:|----------------:|-----------:|
|             0.5 |          0.8629 |       6.98 |
|             0.5 |          0.8629 |       5.37 |
|             0.5 |          0.8629 |       6.13 |
|             0.5 |          0.8629 |       5.29 |


### 3.5. LightGBM

**Гиперпараметр:** `num_leaves` (фиксируем `n_estimators=100, learning_rate=0.1`)

| num_leaves | test_accuracy | time_sec |
|------------|---------------|----------|
| 15         |               |          |
| 31         |               |          |
| 63         |               |          |
| 127        |               |          |

In [19]:
from lightgbm import LGBMClassifier

results_lgbm = []

#(перебор num_leaves, n_jobs=-1)
for leaves in [15, 31, 63, 127]:
    start = time.time()
    clf = LGBMClassifier(n_estimators=100, learning_rate=0.1, num_leaves=leaves, random_state=42, n_jobs=-1)
    clf.fit(X_train, y_train)
    fit_time = time.time() - start
    acc = accuracy_score(y_test, clf.predict(X_test))
    results_lgbm.append({'num_leaves': leaves, 'test_accuracy': round(acc, 4), 'time_sec': round(fit_time, 2)})
    print(f"num_leaves={leaves}: acc={acc:.4f}, time={fit_time:.2f}s")

df_lgbm = pd.DataFrame(results_lgbm)
print("\nТаблица 6. LightGBM")
print(df_lgbm.to_markdown(index=False))

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.129553 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 61063
[LightGBM] [Info] Number of data points in the train set: 2363, number of used features: 2963
[LightGBM] [Info] Start training from score -1.119999
[LightGBM] [Info] Start training from score -1.093126
[LightGBM] [Info] Start training from score -1.083076


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


num_leaves=15: acc=0.9662, time=10.94s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.182253 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 61063
[LightGBM] [Info] Number of data points in the train set: 2363, number of used features: 2963
[LightGBM] [Info] Start training from score -1.119999
[LightGBM] [Info] Start training from score -1.093126
[LightGBM] [Info] Start training from score -1.083076


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


num_leaves=31: acc=0.9594, time=13.40s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.077478 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 61063
[LightGBM] [Info] Number of data points in the train set: 2363, number of used features: 2963
[LightGBM] [Info] Start training from score -1.119999
[LightGBM] [Info] Start training from score -1.093126
[LightGBM] [Info] Start training from score -1.083076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


num_leaves=63: acc=0.9577, time=13.88s
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.070827 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 61063
[LightGBM] [Info] Number of data points in the train set: 2363, number of used features: 2963
[LightGBM] [Info] Start training from score -1.119999
[LightGBM] [Info] Start training from score -1.093126
[LightGBM] [Info] Start training from score -1.083076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain:

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


### 3.6. CatBoost

**Гиперпараметр:** `depth` (фиксируем `iterations=100, learning_rate=0.1`)

| depth | test_accuracy | time_sec |
|-------|---------------|----------|
| 3     |               |          |
| 5     |               |          |
| 7     |               |          |
| 10    |               |          |

In [21]:
!pip install catboost -qq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.1 MB/s eta 0:00:00


In [22]:
from catboost import CatBoostClassifier

results_cat = []

#(перебор depth, verbose=0)
for depth_val in [3, 5, 7, 10]:
    start = time.time()
    clf = CatBoostClassifier(iterations=100, learning_rate=0.1, depth=depth_val, random_state=42, verbose=0)
    clf.fit(X_train, y_train)
    fit_time = time.time() - start
    acc = accuracy_score(y_test, clf.predict(X_test))
    results_cat.append({'depth': depth_val,'test_accuracy': round(acc, 4),'time_sec': round(fit_time, 2)})
    print(f"depth={depth_val}: acc={acc:.4f}, time={fit_time:.2f}s")

df_cat = pd.DataFrame(results_cat)
print("\nТаблица 7. CatBoost")
print(df_cat.to_markdown(index=False))

depth=3: acc=0.9340, time=31.10s
depth=5: acc=0.9425, time=38.11s
depth=7: acc=0.9442, time=124.65s
depth=10: acc=0.9526, time=821.89s

Таблица 7. CatBoost
|   depth |   test_accuracy |   time_sec |
|--------:|----------------:|-----------:|
|       3 |          0.934  |      31.1  |
|       5 |          0.9425 |      38.11 |
|       7 |          0.9442 |     124.65 |
|      10 |          0.9526 |     821.89 |


## 4. Итоговая таблица лучших результатов

In [29]:
# Соберите лучшие результаты из каждой таблицы вручную или автоматически
# Пример структуры:

summary = pd.DataFrame([
    ('Decision Tree', 'nan', 0.8697, 0.67),  # замените 0 на ваши значения
    ('Random Forest', 'nan', 0.9526, 4.65),
    ('Gradient Boosting', 0.5, 0.9662, 36.39),
    ('XGBoost', 0.5, 0.9492, 31.58),
    ('AdaBoost', 0.5, 0.8629, 6.98),
    ('LightGBM', 15, 0.9662, 10.94),
    ('CatBoost', 10, 0.9526, 821.89),
], columns=['Algorithm', 'Best params', 'Best test acc', 'Time (sec)'])

print("Итоговая таблица лучших результатов")
print(summary.to_markdown(index=False))

Итоговая таблица лучших результатов
| Algorithm         |   Best params |   Best test acc |   Time (sec) |
|:------------------|--------------:|----------------:|-------------:|
| Decision Tree     |         nan   |          0.8697 |         0.67 |
| Random Forest     |         nan   |          0.9526 |         4.65 |
| Gradient Boosting |           0.5 |          0.9662 |        36.39 |
| XGBoost           |           0.5 |          0.9492 |        31.58 |
| AdaBoost          |           0.5 |          0.8629 |         6.98 |
| LightGBM          |          15   |          0.9662 |        10.94 |
| CatBoost          |          10   |          0.9526 |       821.89 |


## 5. Вопросы

1. Какой алгоритм показал максимальную точность? Какие параметры к этому привели?

Лучшие результаты показали алгоритмы Gradient Boosting и LightGBM (=0.9662). Параметры, кооторые к жтому привели:

у Gradient Boosting - параметр learning_rate = 0.5;

у LightGBM - параметр num_leaves = 15

2. Какой алгоритм быстрее всего обучался? Во сколько раз он быстрее самого медленного?

Быстрее всего обучился Decision Tree (0.67s), что примерно в 1227 раз быстрее, чем самый медленный алгоритм - CatBoost (821.89s)

3. У каких алгоритмов наблюдалось переобучение? При каких параметрах?

Переобучение наблюдалось как раз у CatBoost (у которого в принципе есть склонность к переобучению, из-за чего и вышли такие высокие показатели по времени). При параметре depth = 10 и наблюдалось переобучение, но при этом здесь жы был самый высокий показатель по accuracy (0.9526).

4. Какой алгоритм вы выбрали бы для продакшн-системы с миллионом текстов? Почему?

Оптимальный вариант - LightGBM, в ходе работы он показал максимальный уровень точности, но при этом, в отличие от Gradient Boosting, с таким же результатом, имеет лучший показатель по времени: LightGBM(10.94s) < Gradient Boosting(36.39s). Для такого большого датасета также хорошо, что в LightGBM используется leaf-wise growth, то есть модлеь смотрит какое разбиение в дереве сильнее всего уменьшит ошибку и развивает только этот "лист", благодаря этому (наверное?) можно избежать переобучения и добиться хороших результатов по accuracy, не затрачивая лишшнего времени.